title: jorgescalona
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: Jorge Escalona
tagline: telecommunications engineer, python dev, odoo, free technologies, gnu / linux admin
about-description: Ability to organize teams and collective work, experience in management and coordination of units operational, convinced of the knowledge tools open knowledgeable and constructor of the legal framework with respect to free technologies, free knowledge and transformation of learning models and education. # Add Discription
pic: yo.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: jorgescalona@riseup.net # Add your Email address
phone: +58 426 9576295 # Add your Phone number
website: attakatara.wordpress.com # Add your website, do not add http://
linkedin: jorgescalona # Add your Linkedin handle
github: jorgescalona # Add your Github handle
gitlab: jorgemustaine # Add your Gitlab handle
twitter: '@jorgemustaine' # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
